# Generated by Django 5.0.3 on 2024-03-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_caterogy_listing_user_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caterogy',
            new_name='Category',
        ),
    ]
